/**
 * Chinese Glossary 2026 - Master Vocabulary Bank
 * Unit 0: 基础导论预备 (Introduction) - 123 Words
 * Sourced directly from AP Chinese Vocabulary Bank By Unit Introduction.xlsx
 */
const DEFAULT_GLOSSARY_DATA = [
  {
    id: "u0_1",
    word: "include / comprise",
    simp: "包括",
    trad: "包括",
    pinyin: "bāo kuò",
    definition: "to include; to comprise; to consist of",
    chineseDef: "包含；容纳在其中（如：费用包括餐费和住宿费）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "常用过渡词"],
    mastered: false
  },
  {
    id: "u0_2",
    word: "contain / embody",
    simp: "包含",
    trad: "包含",
    pinyin: "bāo hán",
    definition: "to contain; to embody; to include",
    chineseDef: "里边含有；包容（如：这句话包含着深刻的哲理）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "常用过渡词"],
    mastered: false
  },
  {
    id: "u0_3",
    word: "always / all along / (neg.) never",
    simp: "从来",
    trad: "從來",
    pinyin: "cóng lái",
    definition: "always; all along; (when followed by 不/没) never",
    chineseDef: "从过去到现在一贯如此（常与否定词连用：从来不、从来没）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "时间与频率"],
    mastered: false
  },
  {
    id: "u0_4",
    word: "originally / at first",
    simp: "本来",
    trad: "本來",
    pinyin: "běn lái",
    definition: "originally; at first; it goes without saying",
    chineseDef: "原先；先前；照理应当（如：他本来打算去，后来改变了主意）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "转折与交代"],
    mastered: false
  },
  {
    id: "u0_5",
    word: "turn out to be / originally",
    simp: "原来",
    trad: "原來",
    pinyin: "yuán lái",
    definition: "as it turns out; originally; former",
    chineseDef: "表示发现了过去不知道的情况（原来是你！）；也指起初",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "发现与转折"],
    mastered: false
  },
  {
    id: "u0_6",
    word: "for example / for instance",
    simp: "比如 / 比方说",
    trad: "比如 / 比方說",
    pinyin: "bǐ rú / bǐ fang shuō",
    definition: "for example; for instance; such as",
    chineseDef: "举例说明的标志词，引出具体事例",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "举例", "过渡连接"],
    mastered: false
  },
  {
    id: "u0_7",
    word: "relatively / compare",
    simp: "比较",
    trad: "比較",
    pinyin: "bǐ jiào",
    definition: "relatively; quite; to compare",
    chineseDef: "副词表示相对程度（比较好）；动词表示对比比较",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "程度与比较"],
    mastered: false
  },
  {
    id: "u0_8",
    word: "must / have to",
    simp: "必须",
    trad: "必須",
    pinyin: "bì xū",
    definition: "must; have to; obligatory",
    chineseDef: "表示事理上和情理上的必要，一定要（如：我们必须努力）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "情态与必要"],
    mastered: false
  },
  {
    id: "u0_9",
    word: "need not / do not have to",
    simp: "不必",
    trad: "不必",
    pinyin: "bú bì",
    definition: "need not; does not have to; unnecessary",
    chineseDef: "表示没有必要、用不着（如：大家不必担心）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "情态与否定"],
    mastered: false
  },
  {
    id: "u0_10",
    word: "need / require",
    simp: "需要",
    trad: "需要",
    pinyin: "xū yào",
    definition: "to need; to require; requirement",
    chineseDef: "应该有或必须有；要求、需要的事物",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "情态与需求"],
    mastered: false
  },
  {
    id: "u0_11",
    word: "really / truly",
    simp: "真的",
    trad: "真的",
    pinyin: "zhēn de",
    definition: "really; truly; genuinely (degree adverb)",
    chineseDef: "表示真实、确实（程度副词，如：真的很高兴、真的太棒了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "程度表达"],
    mastered: false
  },
  {
    id: "u0_12",
    word: "very / extremely",
    simp: "十分",
    trad: "十分",
    pinyin: "shí fēn",
    definition: "very; fully; completely; 100%",
    chineseDef: "程度副词，达到极高程度，相当于“非常、很”",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "程度表达"],
    mastered: false
  },
  {
    id: "u0_13",
    word: "extremely / extraordinarily",
    simp: "非常",
    trad: "非常",
    pinyin: "fēi cháng",
    definition: "extraordinarily; extremely; very",
    chineseDef: "程度副词，格外、十分（如：非常感谢、非常重要）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "程度表达"],
    mastered: false
  },
  {
    id: "u0_14",
    word: "very ... (complement)",
    simp: "……得很",
    trad: "……得很",
    pinyin: "... de hěn",
    definition: "very ...; awfully ... (post-adjective complement, e.g. 好得很)",
    chineseDef: "形容词程度补语，用于形容词后表示程度深（如：大得很、忙得很）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "补语结构"],
    mastered: false
  },
  {
    id: "u0_15",
    word: "too ... / extremely ...",
    simp: "太……了",
    trad: "太……了",
    pinyin: "tài ... le",
    definition: "too ...; extremely ... (e.g. 太好了, 太贵了)",
    chineseDef: "常用固定句式，表示程度过分或极高（如：太美了、太精彩了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "感叹与程度"],
    mastered: false
  },
  {
    id: "u0_16",
    word: "extremely ... (complement)",
    simp: "……极了",
    trad: "……極了",
    pinyin: "... jí le",
    definition: "extremely ...; exceedingly ... (e.g. 精彩极了, 好极了)",
    chineseDef: "形容词补语，放在形容词后表示达到最高极限（如：漂亮极了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "补语结构"],
    mastered: false
  },
  {
    id: "u0_17",
    word: "extraordinarily ... / desperately ...",
    simp: "……得不得了",
    trad: "……得不得了",
    pinyin: "... de bù dé liǎo",
    definition: "extraordinarily ...; terribly ...; beyond measure (e.g. 高兴得不得了)",
    chineseDef: "程度补语，表示程度极高已达到无法形容的地步（如：累得不得了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "补语结构"],
    mastered: false
  },
  {
    id: "u0_18",
    word: "not necessarily / not likely",
    simp: "不见得",
    trad: "不見得",
    pinyin: "bú jiàn de",
    definition: "not necessarily; not likely; not certain",
    chineseDef: "表示不一定、未必如此（如：便宜的东西不见得质量差）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "判断与否定"],
    mastered: false
  },
  {
    id: "u0_19",
    word: "even / so far as to",
    simp: "甚至",
    trad: "甚至",
    pinyin: "shèn zhì",
    definition: "even; so much that; so far as to",
    chineseDef: "连词/副词，提出突出的事例表示递进（如：他甚至连午饭都没吃）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "递进关联"],
    mastered: false
  },
  {
    id: "u0_20",
    word: "especially / special",
    simp: "特别",
    trad: "特別",
    pinyin: "tè bié",
    definition: "especially; particularly; special; extraordinary",
    chineseDef: "格外、十分；特殊的、不同寻常的",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "程度与特指"],
    mastered: false
  },
  {
    id: "u0_21",
    word: "although / feel free to",
    simp: "尽管",
    trad: "儘管",
    pinyin: "jǐn guǎn",
    definition: "although; even though; feel free to (do something)",
    chineseDef: "连词表示转折让步（尽管下雨，他还是去了）；副词表示没有顾虑",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "转折与让步"],
    mastered: false
  },
  {
    id: "u0_22",
    word: "no matter ... / regardless of",
    simp: "不管",
    trad: "不管",
    pinyin: "bù guǎn",
    definition: "no matter (what, who, how); regardless of",
    chineseDef: "连词，表示在任何条件下结果都一样，常与“都/总”连用",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "无条件关联"],
    mastered: false
  },
  {
    id: "u0_23",
    word: "regardless of / no matter what",
    simp: "无论",
    trad: "無論",
    pinyin: "wú lùn",
    definition: "regardless of; no matter what / how / whether",
    chineseDef: "书面连词，表示条件不同而结论不变（无论遇到什么困难都要坚持）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "无条件关联"],
    mastered: false
  },
  {
    id: "u0_24",
    word: "once / formerly / in the past",
    simp: "曾经 / 从前 / 以前",
    trad: "曾經 / 從前 / 以前",
    pinyin: "céng jīng / cóng qián / yǐ qián",
    definition: "once; in the past; formerly; previously",
    chineseDef: "时间词与副词，用于交代过去经历或往昔岁月",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "时间副词", "往事叙述"],
    mastered: false
  },
  {
    id: "u0_25",
    word: "in a little while / shortly",
    simp: "（不/过了）一会儿",
    trad: "（不/過了）一會兒",
    pinyin: "(bù / guò le) yí huì r",
    definition: "in a little while; shortly; before long; after a moment",
    chineseDef: "表示时间短暂（不一会儿：很快；过了一会儿：片刻之后）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "时间短语", "时间流逝"],
    mastered: false
  },
  {
    id: "u0_26",
    word: "in a few days",
    simp: "过几天",
    trad: "過幾天",
    pinyin: "guò jǐ tiān",
    definition: "in a few days; after several days",
    chineseDef: "时间短语，指过了数日之后，多用于对未来的计划交代",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "时间短语", "未来安排"],
    mastered: false
  },
  {
    id: "u0_27",
    word: "in the end / on earth",
    simp: "到底",
    trad: "到底",
    pinyin: "dào dǐ",
    definition: "in the end; after all; (in questions) what on earth",
    chineseDef: "副词，用于疑问句追究实情（到底怎么回事？）；或表示最终",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "疑问与探究"],
    mastered: false
  },
  {
    id: "u0_28",
    word: "after a period of time",
    simp: "过了一段时间",
    trad: "過了一段時間",
    pinyin: "guò le yí duàn shí jiān",
    definition: "after a period of time; after a while",
    chineseDef: "叙事过渡句，表示一段时期或过程过去之后",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "叙事短语", "时间过渡"],
    mastered: false
  },
  {
    id: "u0_29",
    word: "continue / go on",
    simp: "继续",
    trad: "繼續",
    pinyin: "jì xù",
    definition: "to continue; to proceed with; to go on with",
    chineseDef: "动词，活动或状态连下去、不间断（如：继续努力、继续讨论）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "动作持续"],
    mastered: false
  },
  {
    id: "u0_30",
    word: "future / in the future",
    simp: "将来",
    trad: "將來",
    pinyin: "jiāng lái",
    definition: "future; in the future; upcoming",
    chineseDef: "时间名词，现在以后的时间（如：将来的发展、为将来做准备）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "时间概念"],
    mastered: false
  },
  {
    id: "u0_31",
    word: "forever / always",
    simp: "永远",
    trad: "永遠",
    pinyin: "yǒng yuǎn",
    definition: "forever; always; eternally",
    chineseDef: "副词，表示时间长久、永不改变（如：永远记住、永远前进）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "恒久时间"],
    mastered: false
  },
  {
    id: "u0_32",
    word: "not at all / by no means",
    simp: "并（不/没有）",
    trad: "並（不/沒有）",
    pinyin: "bìng (bù / méi yǒu)",
    definition: "(emphasizing negation) actually not; by no means (e.g. 并不难, 并没有)",
    chineseDef: "加在否定词“不”、“没有”前以加强否定语气，反驳或澄清事实",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词句型", "强调否定"],
    mastered: false
  },
  {
    id: "u0_33",
    word: "continuously / constantly",
    simp: "不断（地）",
    trad: "不斷（地）",
    pinyin: "bú duàn (de)",
    definition: "unceasingly; continuously; constantly",
    chineseDef: "副词，持续不间断地（如：不断进步、不断学习）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "频率与状态"],
    mastered: false
  },
  {
    id: "u0_34",
    word: "nonstop / incessantly",
    simp: "不停（地）",
    trad: "不停（地）",
    pinyin: "bù tíng (de)",
    definition: "incessantly; nonstop; without stopping",
    chineseDef: "不停止、连续地进行某种动作（如：雨不停地下着）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "动作连续"],
    mastered: false
  },
  {
    id: "u0_35",
    word: "not as good as / inferior to",
    simp: "不如",
    trad: "不如",
    pinyin: "bù rú",
    definition: "not as good as; inferior to; it would be better to",
    chineseDef: "比较句式，比不上（A不如B）；亦可表示提出更好建议（不如今天去）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词/动词", "比较与选择"],
    mastered: false
  },
  {
    id: "u0_36",
    word: "identical / same",
    simp: "相同",
    trad: "相同",
    pinyin: "xiāng tóng",
    definition: "identical; the same; alike",
    chineseDef: "形容词，彼此一样、没有差异（如：相同点、相同的兴趣）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "形容词", "对比与异同"],
    mastered: false
  },
  {
    id: "u0_37",
    word: "different / difference",
    simp: "不同",
    trad: "不同",
    pinyin: "bù tóng",
    definition: "different; distinct; difference",
    chineseDef: "形容词/名词，不相同、有差别（如：不同文化、不同的看法）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "形容词", "对比与异同"],
    mastered: false
  },
  {
    id: "u0_38",
    word: "part / section",
    simp: "部分",
    trad: "部分",
    pinyin: "bù fen",
    definition: "part; section; portion; component",
    chineseDef: "整体中的局部（如：重要组成部分、一部分人）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "数量与范畴"],
    mastered: false
  },
  {
    id: "u0_39",
    word: "most / majority",
    simp: "大部分",
    trad: "大部分",
    pinyin: "dà bù fen",
    definition: "most (parts); majority; greater part",
    chineseDef: "整体中的绝大多数或主要部分（如：大部分学生）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "数量与比例"],
    mastered: false
  },
  {
    id: "u0_40",
    word: "most / vast majority",
    simp: "大多（数）",
    trad: "大多（數）",
    pinyin: "dà duō (shù)",
    definition: "most; the majority of; mostly",
    chineseDef: "大多数指数量上的绝大部分；大多为副词，相当于“大部分”",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "数词/副词", "数量与比例"],
    mastered: false
  },
  {
    id: "u0_41",
    word: "minority / small number",
    simp: "少数",
    trad: "少數",
    pinyin: "shǎo shù",
    definition: "minority; small number; few",
    chineseDef: "数量少的那一部分（与“多数”相对，如：少数民族、少数情况）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "数量与比例"],
    mastered: false
  },
  {
    id: "u0_42",
    word: "each / every / various",
    simp: "各",
    trad: "各",
    pinyin: "gè",
    definition: "each; every; various; different",
    chineseDef: "指示代词，逐指某范围内的每一个人或物（如：各国、各位、各地）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "代词", "范围与指代"],
    mastered: false
  },
  {
    id: "u0_43",
    word: "all kinds of / various",
    simp: "各种各样（的）",
    trad: "各種各樣（的）",
    pinyin: "gè zhǒng gè yàng (de)",
    definition: "all kinds of; various; a variety of",
    chineseDef: "形容词短语，种类繁多、各式各样（如：各种各样的活动）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "成语短语", "多样与描述"],
    mastered: false
  },
  {
    id: "u0_44",
    word: "first of all / primarily",
    simp: "首先",
    trad: "首先",
    pinyin: "shǒu xiān",
    definition: "first of all; in the first place; primarily",
    chineseDef: "序数连接词，用于论述或介绍事物的第一要点，常与“其次”呼应",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "过渡词", "次序与论述"],
    mastered: false
  },
  {
    id: "u0_45",
    word: "secondly / next",
    simp: "其次",
    trad: "其次",
    pinyin: "qí cì",
    definition: "secondly; next; in the second place",
    chineseDef: "序数连接词，次于第一项的第二要点（首先……其次……）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "过渡词", "次序与论述"],
    mastered: false
  },
  {
    id: "u0_46",
    word: "in addition / furthermore / besides",
    simp: "另外",
    trad: "另外",
    pinyin: "lìng wài",
    definition: "in addition; furthermore; besides; other",
    chineseDef: "连词/副词/代词，在说过的内容之外补充新信息（另外，我想补充一点）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "补充与递进"],
    mastered: false
  },
  {
    id: "u0_47",
    word: "finally / lastly / in the end",
    simp: "最后",
    trad: "最後",
    pinyin: "zuì hòu",
    definition: "finally; in the end; last; ultimately",
    chineseDef: "时间词/连接词，在时间或次序上排在最末位（最后，祝大家成功）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "过渡词", "总结与收尾"],
    mastered: false
  },
  {
    id: "u0_48",
    word: "at last / finally",
    simp: "终于",
    trad: "終於",
    pinyin: "zhōng yú",
    definition: "at last; in the end; finally (after long wait or effort)",
    chineseDef: "副词，表示经过较长过程或很大努力后出现某种结果（终于成功了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "终结与努力"],
    mastered: false
  },
  {
    id: "u0_49",
    word: "do one's best / strive",
    simp: "尽力",
    trad: "盡力",
    pinyin: "jìn lì",
    definition: "to do one's best; to strive with all one's strength",
    chineseDef: "动词，竭尽全力（如：尽力而为、我会尽力帮助你）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "态度与努力"],
    mastered: false
  },
  {
    id: "u0_50",
    word: "as much as possible",
    simp: "尽量",
    trad: "儘量",
    pinyin: "jǐn liàng",
    definition: "as much as possible; to the greatest extent",
    chineseDef: "副词，力求在一定范围内达到最大程度（如：尽量早点来）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "限度与态度"],
    mastered: false
  },
  {
    id: "u0_51",
    word: "as ... as possible",
    simp: "尽可能",
    trad: "儘可能",
    pinyin: "jǐn kě néng",
    definition: "as far as possible; to the best of one's ability",
    chineseDef: "副词短语，在可能范围内达到最高极限（如：尽可能快、尽可能详细）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "短语", "限度与追求"],
    mastered: false
  },
  {
    id: "u0_52",
    word: "surely / certain / definite",
    simp: "一定",
    trad: "一定",
    pinyin: "yí dìng",
    definition: "surely; definitely; certain; fixed",
    chineseDef: "副词表示必定、确凿；形容词表示特定的、固定不移的",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "确定性表达"],
    mastered: false
  },
  {
    id: "u0_53",
    word: "decide / decision",
    simp: "决定",
    trad: "決定",
    pinyin: "jué dìng",
    definition: "to decide; decision; resolve; determine",
    chineseDef: "对如何行动做出决断；也指所作出的主意或结论",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词/名词", "选择与决断"],
    mastered: false
  },
  {
    id: "u0_54",
    word: "definitely / affirmative",
    simp: "肯定",
    trad: "肯定",
    pinyin: "kěn dìng",
    definition: "definitely; certainly; to affirm; positive",
    chineseDef: "副词表示必定无疑；动词表示对事物持认可态度",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词/动词", "确认与肯定"],
    mastered: false
  },
  {
    id: "u0_55",
    word: "could it be that ...?",
    simp: "难道",
    trad: "難道",
    pinyin: "nán dào",
    definition: "could it be that ...? (rhetorical question marker, expecting 'no')",
    chineseDef: "副词，加强反问语气，引人深思（难道你不知道吗？）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "反问与语气"],
    mastered: false
  },
  {
    id: "u0_56",
    word: "no wonder",
    simp: "难怪",
    trad: "難怪",
    pinyin: "nán guài",
    definition: "no wonder; not surprising (having found out the cause)",
    chineseDef: "副词，表示明白了原因后觉得不足为奇（难怪他今天这么高兴）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "因果与恍悟"],
    mastered: false
  },
  {
    id: "u0_57",
    word: "in reality / in fact",
    simp: "实际上",
    trad: "實際上",
    pinyin: "shí jì shang",
    definition: "in reality; actually; as a matter of fact",
    chineseDef: "介词短语/过渡词，指出客观现实与表面现象的不同",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "过渡词", "事实阐释"],
    mastered: false
  },
  {
    id: "u0_58",
    word: "actually / in fact",
    simp: "其实",
    trad: "其實",
    pinyin: "qí shí",
    definition: "actually; in fact; as a matter of fact",
    chineseDef: "副词，表示承上转折，揭示实际真实情况（表面上看很复杂，其实很简单）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "转折与事实"],
    mastered: false
  },
  {
    id: "u0_59",
    word: "other / else",
    simp: "其他",
    trad: "其他",
    pinyin: "qí tā",
    definition: "other; else; the rest",
    chineseDef: "代词，除了提及的人或事物之外的别的（如：其他同学、其他方面）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "代词", "补充与指代"],
    mastered: false
  },
  {
    id: "u0_60",
    word: "among them / in which",
    simp: "其中",
    trad: "其中",
    pinyin: "qí zhōng",
    definition: "among them; in which; of them",
    chineseDef: "代词，在那里面、在某群体或范围内（如：其中有三位是中国人）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "代词", "范围与构成"],
    mastered: false
  },
  {
    id: "u0_61",
    word: "achieve / obtain",
    simp: "取得",
    trad: "取得",
    pinyin: "qǔ dé",
    definition: "to acquire; to obtain; to achieve (results, success)",
    chineseDef: "动词，拿到、得到（常与成就、进步、胜利、好成绩等搭配）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "收获与成果"],
    mastered: false
  },
  {
    id: "u0_62",
    word: "obtain / gain",
    simp: "获得",
    trad: "獲得",
    pinyin: "huò dé",
    definition: "to obtain; to receive; to gain (prizes, praise, approval)",
    chineseDef: "动词，得到、取得（常与奖学金、支持、好评、资格等搭配）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "收获与成果"],
    mastered: false
  },
  {
    id: "u0_63",
    word: "appear / look / seem",
    simp: "显得",
    trad: "顯得",
    pinyin: "xiǎn de",
    definition: "to appear; to look; to seem",
    chineseDef: "动词，表现出某种情形或面貌（穿上这件衣服显得很精神）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "外貌与状态"],
    mastered: false
  },
  {
    id: "u0_64",
    word: "very likely / probably",
    simp: "很可能",
    trad: "很可能",
    pinyin: "hěn kě néng",
    definition: "very likely; most probable; probably",
    chineseDef: "副词短语，表示发生的几率极大、十之八九",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "短语", "推测与概率"],
    mastered: false
  },
  {
    id: "u0_65",
    word: "perhaps / maybe",
    simp: "也许",
    trad: "也許",
    pinyin: "yě xǔ",
    definition: "perhaps; maybe; possibly",
    chineseDef: "副词，表示猜测或不能完全确定（也许他正在路上）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "推测与假设"],
    mastered: false
  },
  {
    id: "u0_66",
    word: "maybe / can't say for sure",
    simp: "说不定",
    trad: "說不定",
    pinyin: "shuō bu dìng",
    definition: "perhaps; maybe; can't say for sure",
    chineseDef: "副词/动词短语，表示无法肯定或可能意外发生（说不定会下雨）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "短语", "推测与口语"],
    mastered: false
  },
  {
    id: "u0_67",
    word: "not necessarily / not certain",
    simp: "不一定",
    trad: "不一定",
    pinyin: "bù yí dìng",
    definition: "not necessarily; not certain; indefinite",
    chineseDef: "副词短语，表示情况不确定或并不必然如此",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "短语", "判断与否定"],
    mastered: false
  },
  {
    id: "u0_68",
    word: "completely / entirely",
    simp: "完全",
    trad: "完全",
    pinyin: "wán quán",
    definition: "completely; entirely; totally; whole",
    chineseDef: "副词，表示毫无遗漏或达到百分之百（我完全同意你的看法）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "程度与完整"],
    mastered: false
  },
  {
    id: "u0_69",
    word: "indeed / truly",
    simp: "的确",
    trad: "的確",
    pinyin: "dí què",
    definition: "really; indeed; truly",
    chineseDef: "副词，完全确实、毫无疑问（这里的风景的确很美）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "证实与强调"],
    mastered: false
  },
  {
    id: "u0_70",
    word: "at all / fundamental",
    simp: "根本",
    trad: "根本",
    pinyin: "gēn běn",
    definition: "(with negative) at all; fundamentally; basic",
    chineseDef: "副词，常与否定词连用表示彻底否定（我根本不知道这件事）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "彻底否定"],
    mastered: false
  },
  {
    id: "u0_71",
    word: "must / have to",
    simp: "非……不可",
    trad: "非……不可",
    pinyin: "fēi ... bù kě",
    definition: "must; have to; nothing but ... will do (strong determination/necessity)",
    chineseDef: "双重否定表示强烈肯定的固定句型（如：他非去不可、非学好不可）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "决心与必要"],
    mastered: false
  },
  {
    id: "u0_72",
    word: "choose / choice",
    simp: "选择",
    trad: "選擇",
    pinyin: "xuǎn zé",
    definition: "to choose; to select; choice; option",
    chineseDef: "挑选；也指挑选出的结果或方案（做出明智的选择）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词/名词", "决定与选择"],
    mastered: false
  },
  {
    id: "u0_73",
    word: "either ... or ...",
    simp: "要么……要么……",
    trad: "要麼……要麼……",
    pinyin: "yào me ... yào me ...",
    definition: "either ... or ... (denoting exclusive alternatives)",
    chineseDef: "连词句型，连接两个互相排斥的选择（要么坐火车，要么坐飞机）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "并列与选择"],
    mastered: false
  },
  {
    id: "u0_74",
    word: "if not ... then ... / either ... or ...",
    simp: "不是……就是……",
    trad: "不是……就是……",
    pinyin: "bú shì ... jiù shì ...",
    definition: "if not A then B; either ... or ...",
    chineseDef: "连词句型，二者必居其一（他周末不是在图书馆，就是在实验室）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "二选其一"],
    mastered: false
  },
  {
    id: "u0_75",
    word: "not ... but rather ...",
    simp: "不是……而是……",
    trad: "不是……而是……",
    pinyin: "bú shì ... ér shì ...",
    definition: "not A but rather B (correcting a misconception)",
    chineseDef: "并列复句句式，否定前者并肯定后者（成功不是靠运气，而是靠努力）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "阐明正误"],
    mastered: false
  },
  {
    id: "u0_76",
    word: "genuine / authentic / real",
    simp: "真的",
    trad: "真的",
    pinyin: "zhēn de",
    definition: "genuine; authentic; real; true (as opposed to fake/imagined)",
    chineseDef: "强调事物本身的真实性与非伪造性（真假之分，这是真的珍珠）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "形容词", "真实与确凿"],
    mastered: false
  },
  {
    id: "u0_77",
    word: "all day long",
    simp: "整天",
    trad: "整天",
    pinyin: "zhěng tiān",
    definition: "all day long; whole day",
    chineseDef: "时间短语，从早到晚一整天（整天呆在家里看书）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "时间名词", "时间跨度"],
    mastered: false
  },
  {
    id: "u0_78",
    word: "just right / coincidentally",
    simp: "正好",
    trad: "正好",
    pinyin: "zhèng hǎo",
    definition: "just right; coincidentally; happen to",
    chineseDef: "恰好、正合适；碰巧（时间、大小正好；我正好要去找你）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词/形容词", "巧合与适宜"],
    mastered: false
  },
  {
    id: "u0_79",
    word: "formal / official",
    simp: "正式",
    trad: "正式",
    pinyin: "zhèng shì",
    definition: "formal; official; regular",
    chineseDef: "符合正规标准、合法手续的（正式会议、正式通知）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "形容词", "正规与仪式"],
    mastered: false
  },
  {
    id: "u0_80",
    word: "between / among",
    simp: "之间",
    trad: "之間",
    pinyin: "zhī jiān",
    definition: "between; among (two or more parties/points)",
    chineseDef: "方位词，在两者或多者相互范围之内（人与人之间、城市之间）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "方位词", "关系与空间"],
    mastered: false
  },
  {
    id: "u0_81",
    word: "have no choice but to",
    simp: "只好",
    trad: "只好",
    pinyin: "zhǐ hǎo",
    definition: "have no choice but to; be forced to",
    chineseDef: "副词，别无其他选择只能如此（下大雨了，我们只好留在室内）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "无奈与抉择"],
    mastered: false
  },
  {
    id: "u0_82",
    word: "important / significant",
    simp: "重要",
    trad: "重要",
    pinyin: "zhòng yào",
    definition: "important; significant; vital; major",
    chineseDef: "形容词，具有重大影响或极大意义的（重要原因、重要任务）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "形容词", "价值与重要性"],
    mastered: false
  },
  {
    id: "u0_83",
    word: "in short / all in all",
    simp: "总之",
    trad: "總之",
    pinyin: "zǒng zhī",
    definition: "in short; in a word; all in all; to sum up",
    chineseDef: "连词，用于段落或论述最后，概括上文所有内容进行总结",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "过渡词", "总结归纳"],
    mastered: false
  },
  {
    id: "u0_84",
    word: "way of doing things / method",
    simp: "做法",
    trad: "做法",
    pinyin: "zuò fǎ",
    definition: "way of doing things; method; practice",
    chineseDef: "名词，处理事情的具体方法或行动（这种做法得到了大家的认可）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "方法与行动"],
    mastered: false
  },
  {
    id: "u0_85",
    word: "aspect / respect / side",
    simp: "方面",
    trad: "方面",
    pinyin: "fāng miàn",
    definition: "aspect; respect; side; field",
    chineseDef: "名词，事物的一个方向或层次（各个方面、在科技方面）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "视角与领域"],
    mastered: false
  },
  {
    id: "u0_86",
    word: "manner / mode / pattern",
    simp: "方式",
    trad: "方式",
    pinyin: "fāng shì",
    definition: "way; style; mode; pattern",
    chineseDef: "名词，说话做事所采取的方法和形式（生活方式、沟通方式）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "形式与途径"],
    mastered: false
  },
  {
    id: "u0_87",
    word: "if it were not for",
    simp: "要不是",
    trad: "要不是",
    pinyin: "yào bu shì",
    definition: "if it were not for; but for (hypothetical counterfactual)",
    chineseDef: "假设连接词，用来提出与实际相反的虚拟假设（要不是你提醒我，我就忘了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "句型", "假设与虚拟"],
    mastered: false
  },
  {
    id: "u0_88",
    word: "otherwise / or else",
    simp: "要不然",
    trad: "要不然",
    pinyin: "yào bu rán",
    definition: "otherwise; or else; if not",
    chineseDef: "连词，表示如果不是这样就将出现另一结果（快点走，要不然就迟到了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "后果与转折"],
    mastered: false
  },
  {
    id: "u0_89",
    word: "otherwise / if not",
    simp: "否则",
    trad: "否則",
    pinyin: "fǒu zé",
    definition: "otherwise; if not; or else (formal equivalent of 要不然)",
    chineseDef: "书面连词，表示如果不是这样（必须准时到达，否则会议将取消）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "条件与后果"],
    mastered: false
  },
  {
    id: "u0_90",
    word: "cause harm to / lead to trouble",
    simp: "害",
    trad: "害",
    pinyin: "hài",
    definition: "to harm; to cause trouble to; to cause someone to suffer",
    chineseDef: "动词，使人受损害、让人遭殃（他粗心大意害得大家重做一遍）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "因果与负面影响"],
    mastered: false
  },
  {
    id: "u0_91",
    word: "advantage / benefit",
    simp: "好处",
    trad: "好處",
    pinyin: "hǎo chu",
    definition: "advantage; benefit; merit; good point",
    chineseDef: "名词，对人或事有益的地方（坚持锻炼对身体有很多好处）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "利益与优势"],
    mastered: false
  },
  {
    id: "u0_92",
    word: "pros and cons / pros and disadvantages",
    simp: "利弊",
    trad: "利弊",
    pinyin: "lì bì",
    definition: "advantages and disadvantages; pros and cons",
    chineseDef: "有利的一面和有害的一面（权衡利弊、各有各的利弊）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词", "对比与思辨"],
    mastered: false
  },
  {
    id: "u0_93",
    word: "mutually / each other",
    simp: "互相",
    trad: "互相",
    pinyin: "hù xiāng",
    definition: "mutually; each other; one another",
    chineseDef: "副词，表示彼此同样对待（互相帮助、互相理解、互相尊重）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "交互与人际"],
    mastered: false
  },
  {
    id: "u0_94",
    word: "even if / even though",
    simp: "即使",
    trad: "即使",
    pinyin: "jí shǐ",
    definition: "even if; even though; granted that",
    chineseDef: "让步连词，表示承认某种假设事实（即使天气不好，我们也要出发）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "让步与假设"],
    mastered: false
  },
  {
    id: "u0_95",
    word: "since / now that",
    simp: "既然",
    trad: "既然",
    pinyin: "jì rán",
    definition: "since; now that; as (followed by 就/那么/也)",
    chineseDef: "因果连词，先提出已知前提再得出推论（既然来了，就多玩几天吧）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "因果与推论"],
    mastered: false
  },
  {
    id: "u0_96",
    word: "suddenly / abruptly",
    simp: "突然",
    trad: "突然",
    pinyin: "tū rán",
    definition: "suddenly; unexpectedly; abrupt",
    chineseDef: "形容词/副词，在短时间内出乎意料地发生（突然下起了暴雨）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词/形容词", "突变与时间"],
    mastered: false
  },
  {
    id: "u0_97",
    word: "although / even though",
    simp: "虽然",
    trad: "雖然",
    pinyin: "suī rán",
    definition: "although; even though; while",
    chineseDef: "转折连词，先承认某种事实，下半句常由“但是/可是”转折",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "转折关系"],
    mastered: false
  },
  {
    id: "u0_98",
    word: "unexpectedly / to one's surprise",
    simp: "竟然 / 竟",
    trad: "竟然 / 竟",
    pinyin: "jìng (rán)",
    definition: "unexpectedly; to one's surprise; go so far as to",
    chineseDef: "副词，表示出乎意料、竟然如此（没想到他竟然做到了）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "意外与感叹"],
    mastered: false
  },
  {
    id: "u0_99",
    word: "however / yet",
    simp: "然而",
    trad: "然而",
    pinyin: "rán'ér",
    definition: "however; yet; but (formal transition)",
    chineseDef: "转折连词，用于句首或分句前，连接语义相反的内容",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "书面转折"],
    mastered: false
  },
  {
    id: "u0_100",
    word: "casual / as one pleases",
    simp: "随便",
    trad: "隨便",
    pinyin: "suí biàn",
    definition: "as one pleases; casual; informal; any",
    chineseDef: "不受限制、随心意（请随便坐）；不加限制（随便什么都可以）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "形容词/动词", "态度与自由"],
    mastered: false
  },
  {
    id: "u0_101",
    word: "fit / suit / appropriate",
    simp: "适合",
    trad: "適合",
    pinyin: "shì hé",
    definition: "to suit; to fit; suitable for",
    chineseDef: "动词，符合实际需要或某种条件（这件衣服非常适合你）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "匹配与适应"],
    mastered: false
  },
  {
    id: "u0_102",
    word: "adapt to / adjust to",
    simp: "适应",
    trad: "適應",
    pinyin: "shì yìng",
    definition: "to adapt to; to adjust to; to get used to",
    chineseDef: "动词，使自己适合新的环境、条件（适应新学校的生活）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "成长与适应"],
    mastered: false
  },
  {
    id: "u0_103",
    word: "general / ordinary / generally",
    simp: "一般",
    trad: "一般",
    pinyin: "yì bān",
    definition: "general; ordinary; commonly; generally",
    chineseDef: "形容词表示平常普通；副词表示通常情况下（一般早上八点上课）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词/形容词", "常规与普通"],
    mastered: false
  },
  {
    id: "u0_104",
    word: "all along / consistently",
    simp: "一向",
    trad: "一向",
    pinyin: "yí xiàng",
    definition: "all along; consistently; from the beginning up to now",
    chineseDef: "副词，表示从过去到现在一直如此（他一向很守时）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "一贯习惯"],
    mastered: false
  },
  {
    id: "u0_105",
    word: "hurriedly / in a rush",
    simp: "急忙",
    trad: "急忙",
    pinyin: "jí máng",
    definition: "hurriedly; hastily; in a rush",
    chineseDef: "副词，心里着急、动作仓促（听到消息后，他急忙跑了出去）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "神态与速度"],
    mastered: false
  },
  {
    id: "u0_106",
    word: "immediately / right away",
    simp: "马上",
    trad: "馬上",
    pinyin: "mǎ shàng",
    definition: "immediately; at once; right away; shortly",
    chineseDef: "副词，表示时间极短，立刻、即刻（我马上就来）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "时间紧迫"],
    mastered: false
  },
  {
    id: "u0_107",
    word: "even / to the point of",
    simp: "甚至",
    trad: "甚至",
    pinyin: "shèn zhì",
    definition: "even; so far as to; to the extent that (emphasizing extreme degree)",
    chineseDef: "用于递进句，强调达到更严重或更突出的程度（不仅没怪他，甚至还鼓励他）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "递进强调"],
    mastered: false
  },
  {
    id: "u0_108",
    word: "almost / nearly / about the same",
    simp: "差不多",
    trad: "差不多",
    pinyin: "chà bu duō",
    definition: "almost; nearly; more or less; about the same",
    chineseDef: "副词表示相差不多（差不多做完了）；形容词表示大体相同",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词/形容词", "近似与估计"],
    mastered: false
  },
  {
    id: "u0_109",
    word: "almost / nearly",
    simp: "几乎",
    trad: "幾乎",
    pinyin: "jī hū",
    definition: "almost; nearly; practically",
    chineseDef: "副词，表示十分接近、差一点点（几乎忘了这件事）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "接近与程度"],
    mastered: false
  },
  {
    id: "u0_110",
    word: "care about / take to heart",
    simp: "在乎",
    trad: "在乎",
    pinyin: "zài hu",
    definition: "to care about; to take to heart; to mind",
    chineseDef: "动词，放在心上、介意（多用于否定：我不在乎别人怎么看）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "心理与态度"],
    mastered: false
  },
  {
    id: "u0_111",
    word: "beneficial to / good for",
    simp: "有益（于）",
    trad: "有益（於）",
    pinyin: "yǒu yì (yú)",
    definition: "beneficial to; advantageous to; good for",
    chineseDef: "动词/形容词短语，对某事物有好处（多吃水果有益于健康）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词短语", "益处与健康"],
    mastered: false
  },
  {
    id: "u0_112",
    word: "regarding / as for",
    simp: "对于",
    trad: "對於",
    pinyin: "duì yú",
    definition: "regarding; as for; with regard to; towards",
    chineseDef: "介词，引出对象或事物范围（对于这个问题，大家有不同意见）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "介词", "对象与指代"],
    mastered: false
  },
  {
    id: "u0_113",
    word: "equal to / tantamount to",
    simp: "等于",
    trad: "等於",
    pinyin: "děng yú",
    definition: "to equal; to be equal to; tantamount to",
    chineseDef: "动词，在数量上相等；或在意义上无异于（放弃就等于失败）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "动词", "等同与比喻"],
    mastered: false
  },
  {
    id: "u0_114",
    word: "as for / as to",
    simp: "至于",
    trad: "至於",
    pinyin: "zhì yú",
    definition: "as for; as to; to go so far as to",
    chineseDef: "连词，表示另提一件事进行说明（至于以后的计划，我们以后再谈）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "话题转换"],
    mastered: false
  },
  {
    id: "u0_115",
    word: "thereupon / as a result",
    simp: "于是",
    trad: "於是",
    pinyin: "yú shì",
    definition: "thereupon; as a result; consequently",
    chineseDef: "承接连词，表示后一事紧接着前一事发生，带有因果相承关系",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "顺承与结果"],
    mastered: false
  },
  {
    id: "u0_116",
    word: "always (often annoyed)",
    simp: "老是",
    trad: "老是",
    pinyin: "lǎo shì",
    definition: "always; all the time (often implying an exasperated or dissatisfied tone)",
    chineseDef: "副词，总是、总是这样（常含有埋怨或不满语气：他老是迟到）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "频率与语气"],
    mastered: false
  },
  {
    id: "u0_117",
    word: "only / merely / but",
    simp: "只是",
    trad: "只是",
    pinyin: "zhǐ shì",
    definition: "only; merely; just; but; however",
    chineseDef: "副词表示仅仅；连词表示轻微转折（我想去，只是今天没有时间）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词/连词", "转折与限制"],
    mastered: false
  },
  {
    id: "u0_118",
    word: "result / as a result",
    simp: "结果",
    trad: "結果",
    pinyin: "jié guǒ",
    definition: "result; outcome; as a result; finally",
    chineseDef: "名词指结局；连词用在下半句表示事情的发展结果",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "名词/连词", "因果与结局"],
    mastered: false
  },
  {
    id: "u0_119",
    word: "and / with / together with",
    simp: "与（和 / 跟）",
    trad: "與（和 / 跟）",
    pinyin: "yǔ (hé / gēn)",
    definition: "and; with; together with (formal connective particle)",
    chineseDef: "连词/介词，书面语常用“与”，口语多用“和、跟”",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "连词", "并列与伴随"],
    mastered: false
  },
  {
    id: "u0_120",
    word: "often / frequently",
    simp: "常常",
    trad: "常常",
    pinyin: "cháng cháng",
    definition: "often; frequently; usually",
    chineseDef: "副词，表示某种行为动作发生的次数多（周末我常常去图书馆）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "频率与习惯"],
    mastered: false
  },
  {
    id: "u0_121",
    word: "regularly / frequently",
    simp: "经常",
    trad: "經常",
    pinyin: "jīng cháng",
    definition: "often; frequently; regularly; day-to-day",
    chineseDef: "副词指常常；形容词指平常、日常的（经常性的活动）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词/形容词", "频率与日常"],
    mastered: false
  },
  {
    id: "u0_122",
    word: "usually / ordinary",
    simp: "平常",
    trad: "平常",
    pinyin: "píng cháng",
    definition: "usually; ordinary; common; customary",
    chineseDef: "时间名词指平时；形容词指普通平常（平常这个时候他都在家）",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "时间/形容词", "日常与普通"],
    mastered: false
  },
  {
    id: "u0_123",
    word: "often / more often than not",
    simp: "往往",
    trad: "往往",
    pinyin: "wǎng wǎng",
    definition: "often; more often than not; frequently (denoting regularity based on experience)",
    chineseDef: "副词，表示根据以往经验，在某种特定条件下经常出现某种情况",
    unit: "Unit 0: Introduction",
    unitZh: "Unit 0: 基础导论预备 (Introduction)",
    unitId: "u0",
    tags: ["AP Chinese", "Unit 0: 基础导论预备", "副词", "规律与频率"],
    mastered: false
  }
];

/**
 * Returns complete combined dataset including Unit 0 (Introduction, 123 words) + AP Chinese Units 1-6 (714 words)
 * Total: 837 words
 */
function getMasterVocabulary() {
  const apList = (typeof AP_CHINESE_DATA !== 'undefined' && Array.isArray(AP_CHINESE_DATA)) ? AP_CHINESE_DATA : [];
  return [...DEFAULT_GLOSSARY_DATA, ...apList];
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DEFAULT_GLOSSARY_DATA, getMasterVocabulary };
}
